"""
Django settings for uniform_inventory project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from django.core.management.utils import get_random_secret_key

# Try to load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable for SECRET_KEY or generate a random one
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
# Use environment variable to control DEBUG mode
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Update ALLOWED_HOSTS with your domain or production IP addresses for security
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Add Railway domain to allowed hosts
if 'RAILWAY_STATIC_URL' in os.environ:
    ALLOWED_HOSTS.append('*.up.railway.app')
    ALLOWED_HOSTS.append('*.railway.app')
    RAILWAY_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
    if RAILWAY_DOMAIN:
        ALLOWED_HOSTS.append(RAILWAY_DOMAIN)
    # Also add explicit Railway domains
    ALLOWED_HOSTS.append('uniform-inventory-system-production.up.railway.app')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',
    # Add security related apps
    'axes',  # For rate limiting login attempts
    'corsheaders',  # For CORS protection
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add whitenoise for static file serving
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware should be at the top
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom security middleware
    'inventory.middleware.SecurityMiddleware',
    # Add security middlewares
    'axes.middleware.AxesMiddleware',  # Should be the last middleware
]

ROOT_URLCONF = 'uniform_inventory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'uniform_inventory.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Configure database for development and Railway
import dj_database_url

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    # If DATABASE_URL is provided (Railway provides this), use it
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=1800),
    }
else:
    # Default SQLite database for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,  # Increase minimum password length for better security
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Toronto'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Static file storage for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # AxesBackend should be first
    'inventory.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = '/inventory/login/'
LOGIN_REDIRECT_URL = '/inventory/dashboard/'
LOGOUT_REDIRECT_URL = '/inventory/login/'

# Session and cookie security
SESSION_COOKIE_AGE = 3600  # 1 hour in seconds
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# If not in debug mode, add these security settings
if not DEBUG:
    # Disable SSL redirect for Railway (it handles SSL at the load balancer)
    if 'RAILWAY_STATIC_URL' in os.environ:
        SECURE_SSL_REDIRECT = False
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    else:
        SECURE_SSL_REDIRECT = True
        
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Django-axes configuration for rate limiting
AXES_FAILURE_LIMIT = 5  # Number of login attempts allowed before blocking
AXES_COOLOFF_TIME = 1  # Locks out for 1 hour after exceeding failure limit
AXES_LOCKOUT_TEMPLATE = 'inventory/lockout.html'  # Create this template later
AXES_LOCKOUT_URL = '/inventory/locked-out/'  # We'll add this URL pattern later

# Fix for django-axes session hash issue
AXES_DISABLE_ACCESS_LOG = True  # Completely disable access logging
AXES_RESET_ON_SUCCESS = True    # Reset counters on successful login

# Additional security settings
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour for password reset links

# Using a more secure password hasher
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    # Add frontend domains that are allowed to access the API
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Add Railway domain to CORS allowed origins
if 'RAILWAY_STATIC_URL' in os.environ:
    RAILWAY_DOMAIN = f"https://{os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')}"
    if RAILWAY_DOMAIN != "https://":
        CORS_ALLOWED_ORIGINS.append(RAILWAY_DOMAIN)
    
    # Also add CSRF trusted origins for Railway
    CSRF_TRUSTED_ORIGINS = [RAILWAY_DOMAIN]
    CSRF_TRUSTED_ORIGINS.append("https://*.up.railway.app")

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

# Only allow cookies in cross-site HTTP requests
CORS_ALLOW_CREDENTIALS = True

# Content Security Policy
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "https://cdn.jsdelivr.net")
CSP_STYLE_SRC = ("'self'", "https://cdn.jsdelivr.net")
CSP_IMG_SRC = ("'self'", "data:")
CSP_FONT_SRC = ("'self'", "https://cdn.jsdelivr.net")
CSP_FRAME_ANCESTORS = ("'none'",)
CSP_FORM_ACTION = ("'self'",)
