# Generated by Django 5.1.6 on 2025-02-13 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformSignOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signoff_date', models.DateField(auto_now_add=True)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='UniformSignOffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('payment_code', models.CharField(choices=[('BW', 'Bi-weekly'), ('FP', 'Full Payment'), ('CP', 'Company Paid'), ('LO', 'Loan')], max_length=2)),
                ('initials', models.CharField(blank=True, max_length=10)),
                ('item_date', models.DateField(blank=True, null=True)),
                ('signoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.uniformsignoff')),
            ],
        ),
    ]
