# Generated by Django 5.1.6 on 2025-03-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_uniformsignoff_uniformsignoffitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniformsignoff',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='uniformsignoffitem',
            name='signoff',
        ),
        migrations.RenameField(
            model_name='uniform',
            old_name='quantity',
            new_name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='uniform',
            name='color',
        ),
        migrations.RemoveField(
            model_name='uniform',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='uniform',
            name='type',
        ),
        migrations.AddField(
            model_name='uniform',
            name='name',
            field=models.CharField(default='Default Uniform', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniform',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uniform',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('payment_option', models.CharField(choices=[('BW', 'Bi-weekly'), ('FP', 'Full Payment'), ('CP', 'Company Paid'), ('LO', 'Loan')], max_length=2)),
                ('loaned', models.BooleanField(default=False)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.employee')),
                ('uniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.uniform')),
            ],
        ),
        migrations.DeleteModel(
            name='UniformAssignment',
        ),
        migrations.DeleteModel(
            name='UniformSignOff',
        ),
        migrations.DeleteModel(
            name='UniformSignOffItem',
        ),
    ]
