# Generated by Django 5.1.6 on 2025-03-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_uniformsignoff_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
