# Generated by Django 5.1.6 on 2025-03-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_transaction_return_date_transaction_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
