# Generated by Django 5.1.6 on 2025-03-14 19:33

from django.db import migrations, models

def populate_employee_ids(apps, schema_editor):
    Employee = apps.get_model('inventory', 'Employee')
    
    # Generate sequential IDs for existing employees
    for i, employee in enumerate(Employee.objects.all(), 1):
        employee.employee_id = f'EMP{i:03d}'
        employee.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_returnrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique Employee ID', max_length=10, null=True),
        ),
        # Run the data migration
        migrations.RunPython(populate_employee_ids),
        # Then make the field unique and not nullable
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique Employee ID', max_length=10, unique=True),
        ),
    ]
