# Generated by Django 5.1.6 on 2025-03-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(help_text='Unique Employee ID (required)', max_length=10, unique=True),
        ),
    ]
