# Generated by Django 5.1.6 on 2025-03-14 20:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='returned_quantity',
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='returnrecord',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_option',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('payroll_deduction', 'Payroll Deduction'), ('no_charge', 'No Charge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uniform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.uniform'),
        ),
        migrations.AlterField(
            model_name='uniform',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='uniform',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='uniform',
            unique_together={('name', 'size')},
        ),
        migrations.CreateModel(
            name='MultiItemTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('payment_option', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('payroll_deduction', 'Payroll Deduction'), ('no_charge', 'No Charge')], max_length=20)),
                ('loaned', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.multiitemtransaction')),
                ('uniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.uniform')),
            ],
        ),
        migrations.CreateModel(
            name='ItemReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.PositiveIntegerField()),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.transactionitem')),
            ],
        ),
    ]
