# Generated by Django 5.1.6 on 2025-03-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_add_multi_transaction_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreturnrecord',
            name='damage_notes',
            field=models.TextField(blank=True, help_text='Description of damage if applicable', null=True),
        ),
        migrations.AddField(
            model_name='itemreturnrecord',
            name='damage_type',
            field=models.CharField(choices=[('none', 'No Damage'), ('wear', 'Normal Wear and Tear'), ('incident', 'Work Incident'), ('other', 'Other Damage')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='itemreturnrecord',
            name='damaged_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of returned items that are damaged/unusable'),
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='damage_notes',
            field=models.TextField(blank=True, help_text='Description of damage if applicable', null=True),
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='damage_type',
            field=models.CharField(choices=[('none', 'No Damage'), ('wear', 'Normal Wear and Tear'), ('incident', 'Work Incident'), ('other', 'Other Damage')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='returnrecord',
            name='damaged_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of returned items that are damaged/unusable'),
        ),
        migrations.AddField(
            model_name='uniform',
            name='damaged_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of damaged/unusable items in inventory'),
        ),
    ]
