# Generated by Django 5.1.6 on 2025-03-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_itemreturnrecord_damage_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='archive_date',
            field=models.DateTimeField(blank=True, help_text='When this employee was archived', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether this employee has been archived'),
        ),
    ]
