# Generated by Django 5.1.6 on 2025-03-18 19:34

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    
    # Check if the superuser already exists to avoid duplicates
    if not User.objects.filter(username='admin').exists():
        superuser = User.objects.create(
            username='admin',
            email='admin@example.com',
            password=make_password('Uniform123!'),  # Using make_password to hash the password
            is_staff=True,
            is_superuser=True,
            is_active=True
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_employee_archive_date_employee_is_archived'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
