# Generated by Django 5.1.6 on 2025-03-18 16:35

from django.db import migrations

def remove_hardcoded_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    
    # Delete only the hardcoded superuser with username 'admin' and email 'admin@example.com'
    # This ensures we don't accidentally delete any other users
    User.objects.filter(username='admin', email='admin@example.com').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_create_superuser'),
    ]

    operations = [
        migrations.RunPython(remove_hardcoded_superuser),
    ]
