# Generated by Django 5.1.6 on 2025-03-18 18:30

from django.db import migrations
from types import FunctionType

def disable_backup_superuser_mechanism(apps, schema_editor):
    """
    Disables the backup superuser creation mechanism by replacing the function
    in migration 0014 with a no-op function that doesn't create any users.
    """
    # Define a replacement function that does nothing
    def noop_ensure_superuser(apps, schema_editor):
        print("Automatic superuser creation has been disabled.")
        return
    
    # Import the migration module that contains the function we want to replace
    try:
        # Import using __import__ instead of direct import
        migrations_module = __import__('inventory.migrations.0014_ensure_superuser_exists', 
                                      fromlist=['ensure_superuser_exists'])
        
        # Replace the function with our no-op function
        if hasattr(migrations_module, 'ensure_superuser_exists'):
            migrations_module.ensure_superuser_exists = noop_ensure_superuser
            print("Successfully disabled automatic superuser creation mechanism")
        else:
            print("Could not find the target function to disable")
    except ImportError:
        print("Could not import the target migration module")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_all_hardcoded_users'),
    ]

    operations = [
        migrations.RunPython(disable_backup_superuser_mechanism),
    ]
