# Generated by Django 5.1.6 on 2025-03-18 19:00

from django.db import migrations
import importlib.util

def completely_remove_backup_superuser_mechanism(apps, schema_editor):
    """
    Completely removes the backup superuser creation mechanism by 
    nullifying the operations in migration 0014_ensure_superuser_exists.
    This is a more thorough approach than just replacing the function.
    """
    try:
        # Find the migration module
        spec = importlib.util.find_spec('inventory.migrations.0014_ensure_superuser_exists')
        if spec is not None:
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            
            # Replace the operations with an empty list
            if hasattr(module, 'Migration') and hasattr(module.Migration, 'operations'):
                module.Migration.operations = []
                print("Successfully removed backup superuser mechanism operations")
                
                # Also nullify the function itself for good measure
                if hasattr(module, 'ensure_superuser_exists'):
                    module.ensure_superuser_exists = lambda *args, **kwargs: None
                    print("Successfully nullified backup superuser function")
            else:
                print("Could not find operations to remove")
        else:
            print("Could not find migration module")
    except Exception as e:
        print(f"Error removing backup superuser mechanism: {str(e)}")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_disable_backup_superuser_creation'),
    ]

    operations = [
        migrations.RunPython(completely_remove_backup_superuser_mechanism),
    ]
