# Generated by Django 5.1.6 on 2025-03-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_backup_superuser_mechanism'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number for tracked items', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
