# Generated by Django 5.1.6 on 2025-03-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_transactionitem_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiitemtransaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Transaction notes, including serial numbers for items', null=True),
        ),
    ]
