# Generated by Django 5.1.6 on 2025-03-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_multiitemtransaction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiitemtransaction',
            name='is_prior_record',
            field=models.BooleanField(default=False, help_text="Mark as 'Prior Record' for transactions that occurred before system implementation. These records will be included in financial calculations but won't affect current inventory levels."),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_prior_record',
            field=models.BooleanField(default=False, help_text="Mark as 'Prior Record' for transactions that occurred before system implementation. These records will be included in financial calculations but won't affect current inventory levels."),
        ),
    ]
