# Generated by Django 5.1.6 on 2025-03-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_equipmentitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentitem',
            options={'ordering': ['name'], 'verbose_name': 'Equipment Item', 'verbose_name_plural': 'Equipment Items'},
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Under Maintenance'), ('repair', 'In Repair'), ('retired', 'Retired')], default='available', max_length=20),
        ),
    ]
